backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News Posts"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "homepage"
    label: "Homepage Text"
    files:
      - file: "content/homepage-text.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Main Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown" }
